version: '3'

services:
  dba:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - dba
    links:
      - dba:dba
